version: "3.5"
services:
  wordpress:
    depends_on:
      - database
    image: "wordpress:latest"
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  database:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    volumes:
      - "localhost:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  wordpress:
  localhost:
